Improve BOSH / kubectl drain
Now, we run `kubectl drain` with the following flags:

- `--force` evicts parentless pods (which won't come back) [new]
- `--delete-local-data` evicts pods that depend on ephemeral local
  storage (volume mounts against `emptyDir:`, mostly) [new]
- `--ignore-daemonsets` doesn't error when it finds pods operated by
  daemonsets (since the controller would just bring them back
  immediately anyway)

These flags should give us the optimal use case of drain-before-update.

diff --git a/jobs/kubelet/templates/bin/drain b/jobs/kubelet/templates/bin/drain
--- a/jobs/kubelet/templates/bin/drain
+++ b/jobs/kubelet/templates/bin/drain
@@ -20,9 +20,9 @@ if pgrep -x kubelet; then
   echo "[$(date)] $BIN/$$: [$NODENAME] currently running the following pods:"
   kubectl get pod -A
   echo "[$(date)] $BIN/$$: [$NODENAME] draining this kubernetes node"
-  kubectl drain --ignore-daemonsets $NODENAME
-  echo "[$(date)] $BIN/$$: [$NODENAME] drain complete; the following pods remain:"
-  kubectl get pod -A
+  kubectl drain --force --ignore-daemonsets --delete-local-data $NODENAME
+  echo "[$(date)] $BIN/$$: [$NODENAME] drain complete; the following pods remain (this may fail, and that's ok):"
+  kubectl get pod -A || true
   echo "[$(date)] $BIN/$$: [$NODENAME] drain script exiting 0."
 else
   echo "[$(date)] $BIN/$$: [$NODENAME] kubelet not running; skipping drain..."
